// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Redactor is an autogenerated mock type for the Redactor type
type Redactor struct {
	mock.Mock
}

// Redact provides a mock function with given fields: content, patterns
func (_m *Redactor) Redact(content string, patterns []string) string {
	ret := _m.Called(content, patterns)

	if len(ret) == 0 {
		panic("no return value specified for Redact")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, []string) string); ok {
		r0 = rf(content, patterns)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewRedactor creates a new instance of Redactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Redactor {
	mock := &Redactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
