// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	sanitizer "github.com/proxikal/hydra/internal/sanitizer"
	mock "github.com/stretchr/testify/mock"
)

// Sanitizer is an autogenerated mock type for the Sanitizer type
type Sanitizer struct {
	mock.Mock
}

// Classify provides a mock function with given fields: chunk
func (_m *Sanitizer) Classify(chunk []byte) sanitizer.ChunkType {
	ret := _m.Called(chunk)

	if len(ret) == 0 {
		panic("no return value specified for Classify")
	}

	var r0 sanitizer.ChunkType
	if rf, ok := ret.Get(0).(func([]byte) sanitizer.ChunkType); ok {
		r0 = rf(chunk)
	} else {
		r0 = ret.Get(0).(sanitizer.ChunkType)
	}

	return r0
}

// ValidateUTF8 provides a mock function with given fields: data
func (_m *Sanitizer) ValidateUTF8(data []byte) []byte {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUTF8")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// NewSanitizer creates a new instance of Sanitizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSanitizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sanitizer {
	mock := &Sanitizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
