// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	security "github.com/proxikal/hydra/internal/security"
	mock "github.com/stretchr/testify/mock"
)

// SizeLimiter is an autogenerated mock type for the SizeLimiter type
type SizeLimiter struct {
	mock.Mock
}

// Limit provides a mock function with given fields: response, maxKB
func (_m *SizeLimiter) Limit(response security.JSONRPCResponse, maxKB int) security.JSONRPCResponse {
	ret := _m.Called(response, maxKB)

	if len(ret) == 0 {
		panic("no return value specified for Limit")
	}

	var r0 security.JSONRPCResponse
	if rf, ok := ret.Get(0).(func(security.JSONRPCResponse, int) security.JSONRPCResponse); ok {
		r0 = rf(response, maxKB)
	} else {
		r0 = ret.Get(0).(security.JSONRPCResponse)
	}

	return r0
}

// NewSizeLimiter creates a new instance of SizeLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSizeLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SizeLimiter {
	mock := &SizeLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
