// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// StateStore is an autogenerated mock type for the StateStore type
type StateStore struct {
	mock.Mock
}

// AddSubscription provides a mock function with given fields: uri
func (_m *StateStore) AddSubscription(uri string) {
	_m.Called(uri)
}

// Clear provides a mock function with no fields
func (_m *StateStore) Clear() {
	_m.Called()
}

// GetInitialize provides a mock function with no fields
func (_m *StateStore) GetInitialize() json.RawMessage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInitialize")
	}

	var r0 json.RawMessage
	if rf, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	return r0
}

// GetSubscriptions provides a mock function with no fields
func (_m *StateStore) GetSubscriptions() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptions")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// RemoveSubscription provides a mock function with given fields: uri
func (_m *StateStore) RemoveSubscription(uri string) {
	_m.Called(uri)
}

// SetInitialize provides a mock function with given fields: params
func (_m *StateStore) SetInitialize(params json.RawMessage) {
	_m.Called(params)
}

// UpdateSubscriptionID provides a mock function with given fields: uri, id
func (_m *StateStore) UpdateSubscriptionID(uri string, id string) {
	_m.Called(uri, id)
}

// NewStateStore creates a new instance of StateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateStore {
	mock := &StateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
