// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	time "time"

	supervisor "github.com/proxikal/hydra/internal/supervisor"
	mock "github.com/stretchr/testify/mock"
)

// Supervisor is an autogenerated mock type for the Supervisor type
type Supervisor struct {
	mock.Mock
}

// LastError provides a mock function with no fields
func (_m *Supervisor) LastError() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PID provides a mock function with no fields
func (_m *Supervisor) PID() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PID")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ResetRestartCounter provides a mock function with no fields
func (_m *Supervisor) ResetRestartCounter() {
	_m.Called()
}

// Restart provides a mock function with no fields
func (_m *Supervisor) Restart() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Restart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with no fields
func (_m *Supervisor) Start() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// State provides a mock function with no fields
func (_m *Supervisor) State() supervisor.ServerState {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 supervisor.ServerState
	if rf, ok := ret.Get(0).(func() supervisor.ServerState); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(supervisor.ServerState)
	}

	return r0
}

// Stop provides a mock function with no fields
func (_m *Supervisor) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Uptime provides a mock function with no fields
func (_m *Supervisor) Uptime() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Uptime")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// NewSupervisor creates a new instance of Supervisor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSupervisor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Supervisor {
	mock := &Supervisor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
